# Generated by Django 5.1 on 2024-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
